<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@2.22">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2.60">
    <parentIds>
      <string>27</string>
    </parentIds>
    <id>28</id>
    <startId>10</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@2.31">
      <startTime>1541775754706</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@2.31">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.16">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1125)</trace>
          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2$1.run(WorkflowRun.java:361)</trace>
          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
          <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
          <trace>java.lang.Thread.run(Thread.java:748)</trace>
        </stackTrace>
        <suppressedExceptions>
          <java.io.IOException>
            <detailMessage>failed to run ps</detailMessage>
            <stackTrace>
              <trace>org.jenkinsci.plugins.docker.workflow.WithContainerStep$Decorator$1.kill(WithContainerStep.java:296)</trace>
              <trace>org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.stop(FileMonitoringTask.java:336)</trace>
              <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.stop(DurableTaskStep.java:390)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:304)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1139)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1128)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:906)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)</trace>
              <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
              <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
              <trace>hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)</trace>
              <trace>jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)</trace>
              <trace>jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)</trace>
              <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
              <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
              <trace>java.lang.Thread.run(Thread.java:748)</trace>
            </stackTrace>
            <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </suppressedExceptions>
          </java.io.IOException>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <jenkins.model.CauseOfInterruption_-UserInterruption>
              <user>wurstgurke</user>
            </jenkins.model.CauseOfInterruption_-UserInterruption>
          </a>
        </causes>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>